# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from jql import jql_pb2 as jql_dot_jql__pb2


class JQLStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListRows = channel.unary_unary(
                '/jql.JQL/ListRows',
                request_serializer=jql_dot_jql__pb2.ListRowsRequest.SerializeToString,
                response_deserializer=jql_dot_jql__pb2.ListRowsResponse.FromString,
                )
        self.GetRow = channel.unary_unary(
                '/jql.JQL/GetRow',
                request_serializer=jql_dot_jql__pb2.GetRowRequest.SerializeToString,
                response_deserializer=jql_dot_jql__pb2.GetRowResponse.FromString,
                )
        self.WriteRow = channel.unary_unary(
                '/jql.JQL/WriteRow',
                request_serializer=jql_dot_jql__pb2.WriteRowRequest.SerializeToString,
                response_deserializer=jql_dot_jql__pb2.WriteRowResponse.FromString,
                )
        self.DeleteRow = channel.unary_unary(
                '/jql.JQL/DeleteRow',
                request_serializer=jql_dot_jql__pb2.DeleteRowRequest.SerializeToString,
                response_deserializer=jql_dot_jql__pb2.DeleteRowResponse.FromString,
                )
        self.Persist = channel.unary_unary(
                '/jql.JQL/Persist',
                request_serializer=jql_dot_jql__pb2.PersistRequest.SerializeToString,
                response_deserializer=jql_dot_jql__pb2.PersistResponse.FromString,
                )


class JQLServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListRows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteRow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Persist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JQLServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListRows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRows,
                    request_deserializer=jql_dot_jql__pb2.ListRowsRequest.FromString,
                    response_serializer=jql_dot_jql__pb2.ListRowsResponse.SerializeToString,
            ),
            'GetRow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRow,
                    request_deserializer=jql_dot_jql__pb2.GetRowRequest.FromString,
                    response_serializer=jql_dot_jql__pb2.GetRowResponse.SerializeToString,
            ),
            'WriteRow': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteRow,
                    request_deserializer=jql_dot_jql__pb2.WriteRowRequest.FromString,
                    response_serializer=jql_dot_jql__pb2.WriteRowResponse.SerializeToString,
            ),
            'DeleteRow': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRow,
                    request_deserializer=jql_dot_jql__pb2.DeleteRowRequest.FromString,
                    response_serializer=jql_dot_jql__pb2.DeleteRowResponse.SerializeToString,
            ),
            'Persist': grpc.unary_unary_rpc_method_handler(
                    servicer.Persist,
                    request_deserializer=jql_dot_jql__pb2.PersistRequest.FromString,
                    response_serializer=jql_dot_jql__pb2.PersistResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jql.JQL', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class JQL(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListRows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/jql.JQL/ListRows',
            jql_dot_jql__pb2.ListRowsRequest.SerializeToString,
            jql_dot_jql__pb2.ListRowsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/jql.JQL/GetRow',
            jql_dot_jql__pb2.GetRowRequest.SerializeToString,
            jql_dot_jql__pb2.GetRowResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteRow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/jql.JQL/WriteRow',
            jql_dot_jql__pb2.WriteRowRequest.SerializeToString,
            jql_dot_jql__pb2.WriteRowResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteRow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/jql.JQL/DeleteRow',
            jql_dot_jql__pb2.DeleteRowRequest.SerializeToString,
            jql_dot_jql__pb2.DeleteRowResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Persist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/jql.JQL/Persist',
            jql_dot_jql__pb2.PersistRequest.SerializeToString,
            jql_dot_jql__pb2.PersistResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
