# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jql/jql.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rjql/jql.proto\x12\x03jql\"\x14\n\x12ListEntriesRequest\"\x15\n\x13ListEntriesResponse\"\x11\n\x0fGetEntryRequest\"\x12\n\x10GetEntryResponse\"\xbb\x01\n\x11WriteEntryRequest\x12\r\n\x05table\x18\x01 \x01(\t\x12\n\n\x02pk\x18\x02 \x01(\t\x12\x32\n\x06\x66ields\x18\x03 \x03(\x0b\x32\".jql.WriteEntryRequest.FieldsEntry\x12\x13\n\x0bupdate_only\x18\x04 \x01(\x08\x12\x13\n\x0binsert_only\x18\x05 \x01(\x08\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x14\n\x12WriteEntryResponse\"/\n\x12\x44\x65leteEntryRequest\x12\r\n\x05table\x18\x01 \x01(\t\x12\n\n\x02pk\x18\x02 \x01(\t\"\x15\n\x13\x44\x65leteEntryResponse\"\x10\n\x0ePersistRequest\"\x11\n\x0fPersistResponse2\xb7\x02\n\x03JQL\x12@\n\x0bListEntries\x12\x17.jql.ListEntriesRequest\x1a\x18.jql.ListEntriesResponse\x12\x37\n\x08GetEntry\x12\x14.jql.GetEntryRequest\x1a\x15.jql.GetEntryResponse\x12=\n\nWriteEntry\x12\x16.jql.WriteEntryRequest\x1a\x17.jql.WriteEntryResponse\x12@\n\x0b\x44\x65leteEntry\x12\x17.jql.DeleteEntryRequest\x1a\x18.jql.DeleteEntryResponse\x12\x34\n\x07Persist\x12\x13.jql.PersistRequest\x1a\x14.jql.PersistResponseB\x0bZ\tjql/jqlpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jql.jql_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\tjql/jqlpb'
  _globals['_WRITEENTRYREQUEST_FIELDSENTRY']._options = None
  _globals['_WRITEENTRYREQUEST_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_LISTENTRIESREQUEST']._serialized_start=22
  _globals['_LISTENTRIESREQUEST']._serialized_end=42
  _globals['_LISTENTRIESRESPONSE']._serialized_start=44
  _globals['_LISTENTRIESRESPONSE']._serialized_end=65
  _globals['_GETENTRYREQUEST']._serialized_start=67
  _globals['_GETENTRYREQUEST']._serialized_end=84
  _globals['_GETENTRYRESPONSE']._serialized_start=86
  _globals['_GETENTRYRESPONSE']._serialized_end=104
  _globals['_WRITEENTRYREQUEST']._serialized_start=107
  _globals['_WRITEENTRYREQUEST']._serialized_end=294
  _globals['_WRITEENTRYREQUEST_FIELDSENTRY']._serialized_start=249
  _globals['_WRITEENTRYREQUEST_FIELDSENTRY']._serialized_end=294
  _globals['_WRITEENTRYRESPONSE']._serialized_start=296
  _globals['_WRITEENTRYRESPONSE']._serialized_end=316
  _globals['_DELETEENTRYREQUEST']._serialized_start=318
  _globals['_DELETEENTRYREQUEST']._serialized_end=365
  _globals['_DELETEENTRYRESPONSE']._serialized_start=367
  _globals['_DELETEENTRYRESPONSE']._serialized_end=388
  _globals['_PERSISTREQUEST']._serialized_start=390
  _globals['_PERSISTREQUEST']._serialized_end=406
  _globals['_PERSISTRESPONSE']._serialized_start=408
  _globals['_PERSISTRESPONSE']._serialized_end=425
  _globals['_JQL']._serialized_start=428
  _globals['_JQL']._serialized_end=739
# @@protoc_insertion_point(module_scope)
